routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::resource('escuelas', 'EscuelaController');
Route::resource('estudiantes', 'EstudianteController');
Route::resource('servicios', 'ServicioController');
Route::resource('asignaciones', 'EstudianteServicioController');

app/Escuela.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Escuela extends Model
{
    protected $table =  "escuelas";

    protected $fillable = ['id','nombreEsc'];
    public $timestamps = false;

    public function estudiantes(){
        return $this->hasMany(Estudiante::class);
    }
}

app/Http/Controllers/EscuelaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Escuela as Escuela;

class EscuelaController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$escuelas = Escuela::all();
		return view('sistema.escuelas.index',compact('escuelas'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('sistema.escuelas.agregar');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{

		$data = request()->validate([
				'nombreEsc' => 'required|unique:escuelas,nombreEsc',
				
		], [
			'nombreEsc.required' => 'El campo nombre de la escuela es obligatorio',
			'nombreEsc.unique' => 'El nombre de la escuela ya esta en uso'
		]);
		$escuela = new Escuela;
		$escuela->nombreEsc = $data['nombreEsc'];
		$alert="success";
			if($escuela->save()){
				$dato="Se guardo la escuela";
			}else{
				$dato="No pudo guardar la escuela";
				$alert="danger";
			}

			return back()->with('dato',$dato)->with('alert',$alert);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$escuela = Escuela::findOrFail($id);
		return view('sistema.escuelas.editar',compact('escuela'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$data = request()->validate([
				'nombreEsc' => 'required',
				
		], [
			'nombreEsc.required' => 'El campo nombre de la escuela es obligatorio',
			
		]);
		$escuela = Escuela::findOrFail($id);
		$escuela->nombreEsc = $data['nombreEsc'];
		
		$alert="success";
			if($escuela->save()){
				$dato="Se edito la escuela";
			}else{
				$dato="No pudo editar la escuela";
				$alert="danger";
			}

			return back()->with('dato',$dato)->with('alert',$alert);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		$escuela = Escuela::findOrFail($id);
		$alert="success";
			if($escuela->delete()){
				$dato="Se elimino la escuela";
			}else{
				$dato="No pudo eliminar la escuela";
				$alert="danger";
			}

			return back()->with('dato',$dato)->with('alert',$alert);
	}
}

resources/views/sistema/escuelas/agregar.blade.php
@extends('layouts.app')
@section('title','Agregar escuela')
@section('content')

<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header text-center">
			<h1 class="text-center text-primary"> Agregar escuela</h1>
      
		</div>
    @include('layouts.info')
		<div class="card-body">
			{!! Form::open(['route' => 'escuelas.store']) !!}
			@include('sistema.escuelas.form')
			{!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

resources/views/sistema/escuelas/editar.blade.php
@extends('layouts.app')
@section('title','Editar escuela')
@section('content')

<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header text-center">
			<h1 class="text-center text-primary">Editar Escuela</h1>
		
		</div>
		<div class="card-body">
		@include('layouts.info')
			{!! Form::model($escuela, ['route' => ['escuelas.update',$escuela->id],'method' => 'PATCH']) !!}
			@include('sistema.escuelas.form')
			{!! Form::close() !!}
		</div>
		
	</div>
</div>

@endsection

resources/views/sistema/escuelas/form.blade.php
<div class="row">
	
    <div class="form-group col-sm-8 col-md-8 col-xs-8 mx-auto">
      {!! Form::label('nombreEsc','Nombre de la escuela:', ['class' => 'text-primary']);!!}
      {!! Form::text('nombreEsc',old('nombreEsc'), ['class' => 'form-control ',
      'name'=>'nombreEsc','id'=>'nombreEsc']);!!}
      
    </div>
    <div class="form-group col-sm-4 col-md-4 col-xs-4 mx-auto my-4">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Aceptar</button>
    </div>
  
</div>

resources/views/sistema/escuelas/index.blade.php
@extends('layouts.app')
@section('title','Listado escuelas')
@section('content')
<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header">
			<h1 class="text-center text-success">Listado de Escuelas</h1>
			<a class="btn btn-success btn-block" href="{{route('escuelas.create')}}">Agregar <span
					class="mdi mdi-plus"></span></a>
		</div>
		<div class="card-body">
		@include('layouts.info')
			<table class="table table-hover ">
				<thead>
					<tr>
						<th scope="col">id</th>
						<th scope="col">Nombre de la escuela</th>
						
						<th scope="col" colspan="2" class="text-center">Operaciones</th>
					</tr>
				</thead>
				<tbody>
					
					@foreach($escuelas as $e)
					<tr>
							<td>{{$e->id}}</td>
							<td>{{$e->nombreEsc}}</td>
							<td><a href="{{route('escuelas.edit',$e->id)}}" class="btn btn-warning">Editar</a></td>
							<td>
							{!! Form::open(['route' => ['escuelas.destroy',$e->id],'method'=>'DELETE']) !!}
								<button type="submit" class="btn btn-danger">Eliminar</button>
							{!! Form::close() !!}
							</td>
					</tr>			
					@endforeach
					
				</tbody>

			</table>
			
		</div>
	</div>
</div>
@endsection