routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::resource('escuelas', 'EscuelaController');
Route::resource('estudiantes', 'EstudianteController');
Route::resource('servicios', 'ServicioController');
Route::resource('asignaciones', 'EstudianteServicioController');

app/Estudiante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Estudiante extends Model
{
    protected $table =  "estudiantes";

    protected $fillable = ['id','nombreEst','edad','sexo','tipo','escuela_id'];
    public $timestamps = false;

    public function escuela(){
      return $this->belongsTo(Escuela::class,'escuela_id');
    }

    public function estudianteservicios(){
      return $this->hasMany(Estudianteservicio::class);
    }
}

app/Http/Controllers/EstudianteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Estudiante as Estudiante;
use App\Escuela as Escuela;
class EstudianteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estudiantes = Estudiante::all();
        return view('sistema.estudiantes.index',compact('estudiantes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $escuelas = Escuela::all();
        return view('sistema.estudiantes.agregar',compact('escuelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->validate([
            'nombreEst'=>'required',
            'apellidos'=> 'required',
            'edad'=>'required|numeric',
            'sexo'=>'required',
            'tipo'=>'required',
            'escuela_id'=>'required'
        ],[
            'nombreEst.required'=>'El nombre es requerido',
            'apellidos.required'=>'El apellido es requerido',
            'edad.required'=>'La edad es requerida',
            'edad.numeric'=>'La edad debe ser numerico',
            'sexo.required'=>'El sexo es requerido',
            'tipo.required'=>'El tipo es requerido',
            'escuela_id.required'=>'La escuela es requerido',
        ]);

        $estudiante = new Estudiante;
        $estudiante->nombreEst = $data['nombreEst'];
        $estudiante->apellidos = $data['apellidos'];
        $estudiante->edad = $data['edad'];
        $estudiante->sexo = $data['sexo'];
        $estudiante->tipo = $data['tipo'];
        $estudiante->escuela_id = $data['escuela_id'];
        
        $alert="success";
		if($estudiante->save()){
			$dato="Se guardo el estudiante";
		}else{
			$dato="No pudo guardar el estudiante";
			$alert="danger";
		}

		return back()->with('dato',$dato)->with('alert',$alert);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $estudiante =  Estudiante::findOrFail($id);
        $escuelas = Escuela::all();
        return view('sistema.estudiantes.editar',compact(['estudiante','escuelas']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = request()->validate([
            'nombreEst'=>'required',
            'apellidos'=> 'required',
            'edad'=>'required|numeric',
            'sexo'=>'required',
            'tipo'=>'required',
            'escuela_id'=>'required'
        ],[
            'nombreEst.required'=>'El nombre es requerido',
            'apellidos.required'=>'El apellido es requerido',
            'edad.required'=>'La edad es requerida',
            'edad.numeric'=>'La edad debe ser numerico',
            'sexo.required'=>'El sexo es requerido',
            'tipo.required'=>'El tipo es requerido',
            'escuela_id.required'=>'La escuela es requerido',
        ]);

        $estudiante = Estudiante::findOrFail($id);
        $estudiante->nombreEst = $data['nombreEst'];
        $estudiante->apellidos = $data['apellidos'];
        $estudiante->edad = $data['edad'];
        $estudiante->sexo = $data['sexo'];
        $estudiante->tipo = $data['tipo'];
        $estudiante->escuela_id = $data['escuela_id'];
        
        $alert="success";
		if($estudiante->save()){
			$dato="Se edito el estudiante";
		}else{
			$dato="No pudo editar el estudiante";
			$alert="danger";
		}

		return back()->with('dato',$dato)->with('alert',$alert);   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $estudiante = Estudiante::findOrFail($id);
		$alert="success";
			if($estudiante->delete()){
				$dato="Se elimino el estudiante";
			}else{
				$dato="No pudo eliminar el estudiante";
				$alert="danger";
			}

			return back()->with('dato',$dato)->with('alert',$alert);
    }
}

resources/views/sistema/estudiantes/agregar.blade.php
@extends('layouts.app')
@section('title','Agregar estudiante')
@section('content')

<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header text-center">
			<h1 class="text-center text-primary"> Agregar estudiante</h1>
      
		</div>
    @include('layouts.info')
		<div class="card-body">
			{!! Form::open(['route' => 'estudiantes.store']) !!}
			@include('sistema.estudiantes.form')
			{!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

resources/views/sistema/estudiantes/editar.blade.php
@extends('layouts.app')
@section('title','Editar estudiante')
@section('content')

<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header text-center">
			<h1 class="text-center text-primary">Editar estudiante</h1>
		
		</div>
		<div class="card-body">
		@include('layouts.info')
			{!! Form::model($estudiante, ['route' => ['estudiantes.update',$estudiante->id],'method' => 'PATCH']) !!}
			@include('sistema.estudiantes.form')
			{!! Form::close() !!}
		</div>
		
	</div>
</div>

@endsection

resources/views/sistema/estudiantes/form.blade.php
<div class="form-group col-sm-12 col-md-12 col-xs-12 mx-auto">
  <div class="row">
        <div class="form-group col-sm-4 col-md-4 col-xs-4 ">
          {!! Form::label('nombreEst','Nombre del estudiante:', ['class' => 'text-primary']);!!}
          {!! Form::text('nombreEst',old('nombreEst'), ['class' => 'form-control ',
          'name'=>'nombreEst','id'=>'nombreEst']);!!}
          
        </div>
        <div class="form-group col-sm-4 col-md-4 col-xs-4 ">
          {!! Form::label('apellidos','Apellidos:', ['class' => 'text-primary']);!!}
          {!! Form::text('apellidos',old('apellidos'), ['class' => 'form-control ',
          'name'=>'apellidos','id'=>'apellidos']);!!}
          
        </div>
        <div class="form-group col-sm-4 col-md-4 col-xs-4">
          {!! Form::label('edad','Edad:', ['class' => 'text-primary']);!!}
          {!! Form::text('edad',old('edad'), ['class' => 'form-control ',
          'name'=>'edad','id'=>'edad']);!!}    
        </div>
  </div>
</div>  
<div class="form-group col-sm-12 col-md-12 col-xs-12 mx-auto">
  <div class="row">
    <div class="form-group col-sm-4 col-md-4 col-xs-4 mx-auto">
      {!! Form::label('sexo','Sexo:', ['class' => 'text-primary']);!!}
      {!! Form::select('sexo', ['Hombre' => 'Hombre', 'Mujer' => 'Mujer'], null, ['placeholder' => 'Seleccione por favor','class'=>'form-control']);!!}
      
    </div>
    <div class="form-group col-sm-4 col-md-4 col-xs-4 mx-auto">
      {!! Form::label('tipo','Tipo:', ['class' => 'text-primary']);!!}
      {!! Form::select('tipo', ['Escolarizado' => 'Escolarizado', 'Sabatino' => 'Sabatino'], null, ['placeholder' => 'Seleccione por favor','class'=>'form-control']);!!}
      
    </div>
    <div class="form-group col-sm-4 col-md-4 col-xs-4 mx-auto">
      {!! Form::label('nombreEsc','Nombre de la escuela:', ['class' => 'text-primary']);!!}
      @if(isset($estudiante))
      <select class="form-control" name="escuela_id" id="escuela_id">
        <option value="">Seleccione escuela por favor..</option>
        @foreach ($escuelas as $esc)
        <option value="{{$esc->id}}" {{ $estudiante->escuela_id == $esc->id ? 'selected':''}}>
          {{$esc->nombreEsc}}</option>

        @endforeach
      </select>
      @else
      <select class="form-control" name="escuela_id" id="escuela_id">
        <option value="">Seleccione escuela por favor..</option>
        @foreach ($escuelas as $esc)
        <option value="{{$esc->id}}" {{ old('escuela_id') == $esc->id ? 'selected' : ''}}>
          {{$esc->nombreEsc}}</option>

        @endforeach
      </select>
      @endif

      
    </div>
  </div>
</div>      

<div class="row">
  <div class="form-group col-sm-4 col-md-4 col-xs-4 mx-auto my-4">
    <button type="submit" class="btn btn-primary btn-lg btn-block">Aceptar</button>
  </div>
</div>

resources/views/sistema/estudiantes/index.blade.php
@extends('layouts.app')
@section('title','Listado Estudiantes')
@section('content')
<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header">
			<h1 class="text-center text-success">Listado de Estudiantes</h1>
			<a class="btn btn-success btn-block" href="{{route('estudiantes.create')}}">Agregar <span
					class="mdi mdi-plus"></span></a>
		</div>
		<div class="card-body">
		@include('layouts.info')
			<table class="table table-hover ">
				<thead>
					<tr>
						<th scope="col">id</th>
						<th scope="col">Nombre completo</th>
						<th scope="col">Edad</th>
						<th scope="col">Sexo</th>
						<th scope="col">Tipo</th>
						<th scope="col">Nombre de la Escuela</th>
						<th scope="col" colspan="2" class="text-center">Operaciones</th>
					</tr>
				</thead>
				<tbody>
					
					@foreach($estudiantes as $e)
					<tr>
							<td>{{$e->id}}</td>
							<td>{{$e->nombreEst}} {{$e->apellidos}}</td>
							<td>{{$e->edad}}</td>
							<td>{{$e->sexo}}</td>
							<td>{{$e->tipo}}</td>
							<td>{{$e->escuela->nombreEsc}}</td>
							<td><a href="{{route('estudiantes.edit',$e->id)}}" class="btn btn-warning">Editar</a></td>
							<td>
							{!! Form::open(['route' => ['estudiantes.destroy',$e->id],'method'=>'DELETE']) !!}
								<button type="submit" class="btn btn-danger">Eliminar</button>
							{!! Form::close() !!}
							</td>
					</tr>			
					@endforeach
					
				</tbody>

			</table>
			
		</div>
	</div>
</div>
@endsection