routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::resource('escuelas', 'EscuelaController');
Route::resource('estudiantes', 'EstudianteController');
Route::resource('servicios', 'ServicioController');
Route::resource('asignaciones', 'EstudianteServicioController');

app/Servicio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Servicio extends Model
{
    protected $table= "servicios";
    protected $fillable = ['id','nombreSer','descripcion'];
    public $timestamps = false;

    public function estudianteservicios(){
        return $this->hasMany(Estudianteservicio::class);
    }
}

app/Http/Controllers/ServicioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Servicio as Servicio;
class ServicioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $servicios = Servicio::all();
        return view('sistema.servicios.index',compact('servicios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sistema.servicios.agregar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->validate([
            'nombreSer'=>'required|unique:servicios,nombreSer',
            'descripcion'=>'required'
        ],[
            'nombreSer.required'=>'EL nombre del servicio debe ser requerido',
            'nombreSer.unique'=>'EL nombre del servicio debe ser unico',
            'descripcion.required' =>'La descripcion debe ser requerida'
        ]);

        $servicio = new Servicio;
        $servicio->nombreSer = $data['nombreSer'];
        $servicio->descripcion = $data['descripcion'];
        $alert="success";
		if($servicio->save()){
			$dato="Se guardo el servicio";
		}else{
			$dato="No pudo guardar el servicio";
			$alert="danger";
		}

		return back()->with('dato',$dato)->with('alert',$alert);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $servicio = Servicio::findOrFail($id);
        return view('sistema.servicios.editar',compact('servicio')); 

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = request()->validate([
            'nombreSer'=>'required',
            'descripcion'=>'required'
        ],[
            'nombreSer.required'=>'EL nombre del servicio debe ser requerido',
            'descripcion.required' =>'La descripcion debe ser requerida'
        ]);
        
        $servicio = Servicio::findOrFail($id);
        $servicio->nombreSer = $data['nombreSer'];
        $servicio->descripcion = $data['descripcion'];
        $alert="success";
		if($servicio->save()){
			$dato="Se edito el servicio";
		}else{
			$dato="No pudo editar el servicio";
			$alert="danger";
		}

		return back()->with('dato',$dato)->with('alert',$alert);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $servicio = Servicio::findOrFail($id);
        $alert="success";
		if($servicio->delete()){
			$dato="Se elimino el servicio";
		}else{
			$dato="No pudo eliminar el servicio";
			$alert="danger";
		}

		return back()->with('dato',$dato)->with('alert',$alert);
    }
}

resources/views/sistema/servicios/agregar.blade.php
@extends('layouts.app')
@section('title','Agregar servicio')
@section('content')

<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header text-center">
			<h1 class="text-center text-primary"> Agregar servicio</h1>
      
		</div>
    @include('layouts.info')
		<div class="card-body">
			{!! Form::open(['route' => 'servicios.store']) !!}
			@include('sistema.servicios.form')
			{!! Form::close() !!}
		</div>
	</div>
</div>

@endsection

resources/views/sistema/servicios/editar.blade.php
@extends('layouts.app')
@section('title','Editar servicio')
@section('content')

<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header text-center">
			<h1 class="text-center text-primary">Editar servicio</h1>
		
		</div>
		<div class="card-body">
		@include('layouts.info')
			{!! Form::model($servicio, ['route' => ['servicios.update',$servicio->id],'method' => 'PATCH']) !!}
			@include('sistema.servicios.form')
			{!! Form::close() !!}
		</div>
		
	</div>
</div>

@endsection

resources/views/sistema/servicios/form.blade.php
<div class="row">
	
    <div class="form-group col-sm-8 col-md-8 col-xs-8 mx-auto">
      {!! Form::label('nombreSer','Nombre del Servicio:', ['class' => 'text-primary']);!!}
      {!! Form::text('nombreSer',old('nombreSer'), ['class' => 'form-control ',
      'name'=>'nombreSer','id'=>'nombreSer']);!!}
      
    </div>
    <div class="form-group col-sm-8 col-md-8 col-xs-8 mx-auto">
      {!! Form::label('descripcion','Descripcion:', ['class' => 'text-primary']);!!}
      {!! Form::textarea('descripcion',old('descripcion'), ['class' => 'form-control ',
      'name'=>'descripcion','id'=>'descripcion']);!!}
      
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-4 col-md-4 col-xs-4 mx-auto my-4">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Aceptar</button>
    </div>
</div>

resources/views/sistema/servicios/index.blade.php
@extends('layouts.app')
@section('title','Listado servicios')
@section('content')
<div class="col-sm-12 col-md-12 col-xs-12 mx-auto">
	<div class="card">
		<div class="card-header">
			<h1 class="text-center text-success">Listado de servicios</h1>
			<a class="btn btn-success btn-block" href="{{route('servicios.create')}}">Agregar <span
					class="mdi mdi-plus"></span></a>
		</div>
		<div class="card-body">
		@include('layouts.info')
			<table class="table table-hover ">
				<thead>
					<tr>
						<th scope="col">id</th>
						<th scope="col">Nombre del servicio</th>
						<th scope="col">Descripcion</th>
						<th scope="col" colspan="2" class="text-center">Operaciones</th>
					</tr>
				</thead>
				<tbody>
					
					@foreach($servicios as $s)
					<tr>
							<td>{{$s->id}}</td>
							<td>{{$s->nombreSer}}</td>
							<td>{{$s->descripcion}}</td>
							<td><a href="{{route('servicios.edit',$s->id)}}" class="btn btn-warning">Editar</a></td>
							<td>
							{!! Form::open(['route' => ['servicios.destroy',$s->id],'method'=>'DELETE']) !!}
								<button type="submit" class="btn btn-danger">Eliminar</button>
							{!! Form::close() !!}
							</td>
					</tr>			
					@endforeach
					
				</tbody>

			</table>
			
		</div>
	</div>
</div>
@endsection