routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::resource('escuelas', 'EscuelaController');
Route::resource('estudiantes', 'EstudianteController');
Route::resource('servicios', 'ServicioController');
Route::resource('asignaciones', 'EstudianteServicioController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- CSRF Token -->
		<meta name="csrf-token" content="{{ csrf_token() }}">

		<title>@yield('title')</title>

		<!-- Scripts -->
		<script src="{{ asset('js/app.js') }}" defer></script>

		<!-- Fonts -->
		<link rel="dns-prefetch" href="//fonts.gstatic.com">
		<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

		<!-- Styles -->
		<link href="{{ asset('css/app.css') }}" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>
		<div id="app">
				<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
						<div class="container">
								<a class="navbar-brand" href="{{ url('/') }}">
										<h5>SISTEMA DE CONTROL</h5>
								</a>
								<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
										<span class="navbar-toggler-icon"></span>
								</button>

								<div class="collapse navbar-collapse" id="navbarSupportedContent">
										<!-- Left Side Of Navbar -->
										<ul class="navbar-nav mr-auto">

										</ul>

										<!-- Right Side Of Navbar -->
										<ul class="navbar-nav ml-auto">
												<!-- Authentication Links -->
												@guest
														<li class="nav-item">
																<a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
														</li>
														@if (Route::has('register'))
																<li class="nav-item">
																		<a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
																</li>
														@endif
												@else
														<li class="nav-item">
																<a class="nav-link" href="{{route('escuelas.index')}}">Escuelas</a>
														</li>
														<li class="nav-item">
																<a class="nav-link" href="{{route('estudiantes.index')}}">Estudiantes</a>
														</li>
														<li class="nav-item">
																<a class="nav-link" href="{{route('servicios.index')}}">Servicios</a>
														</li>
														<li class="nav-item">
																<a class="nav-link" href="{{route('asignaciones.index')}}">Asignación de servicios</a>
														</li>

														<li class="nav-item dropdown">
																<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
																		{{ Auth::user()->name }} <span class="caret"></span>
																</a>

																<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
																		<a class="dropdown-item" href="{{ route('logout') }}"
																			 onclick="event.preventDefault();
																										 document.getElementById('logout-form').submit();">
																				{{ __('Logout') }}
																		</a>

																		<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
																				@csrf
																		</form>
																</div>
														</li>
												@endguest
										</ul>
								</div>
						</div>
				</nav>

				<main class="py-4">
						
						@yield('content')
				</main>
		</div>
</body>
</html>

resources/views/layouts/info.blade.php
@if(Session::has('dato') || Session::has('alert') )
<div class="container my-2">
	<div class="alert alert-{{Session::get('alert')}} col-md-7 offset-md-2"  >
		{{ Session::get('dato') }}
	</div>

</div>
@endif
@if($errors->any())
<div class="shadow alert alert-danger" >
	@if($errors->any())
	<ul>
		@foreach($errors->all() as $error)
		<li>{{ $error }}</li>
		@endforeach
	</ul>
	@endif
</div>
@endif



<script>
	$('.alert').slideDown();
	setTimeout(()=> $('.alert').slideUp(),10000)
</script>